export const leagues = [
  { name: 'NBA' },
  { name: 'WNBA' },
  { name: 'NFL' },
  { name: 'MLB' },
  { name: 'NHL' },
  { name: 'V League' }
];

export const playerCounts = [
  { label: 'Top 10', value: '10' },
  { label: 'Top 50', value: '50' }
];

export const leagueStatsData = {
  NBA: [
    { label: 'Avg Points', key: 'avgPoints' },
    { label: 'Points', key: 'points' },
    { label: 'Rebounds', key: 'rebounds' },
    { label: 'Avg Rebounds', key: 'avgRebounds' },
    { label: 'Offensive Rebounds', key: 'offensiveRebounds' },
    { label: 'Defensive Rebounds', key: 'defensiveRebounds' },
    { label: 'Assists', key: 'assists' },
    { label: 'Avg Assists', key: 'avgAssists' },
    { label: 'Blocks', key: 'blocks' },
    { label: 'Avg Blocks', key: 'avgBlocks' },
    { label: 'Steals', key: 'steals' },
    { label: 'Avg Steals', key: 'avgSteals' },
    { label: 'Turnovers', key: 'turnovers' },
    { label: 'Avg Turnovers', key: 'avgTurnovers' },
    { label: 'Fouls', key: 'fouls' },
    { label: 'Avg Fouls', key: 'avgFouls' },
    { label: 'Field Goals Made', key: 'fieldGoalsMade' },
    { label: 'Field Goals Attempted', key: 'fieldGoalsAttempted' },
    { label: 'Field Goal %', key: 'fieldGoalPct' },
    { label: '3PT Made', key: 'threePointFieldGoalsMade' },
    { label: '3PT Attempted', key: 'threePointFieldGoalsAttempted' },
    { label: '3PT %', key: 'threePointFieldGoalPct' },
    { label: 'Free Throws Made', key: 'freeThrowsMade' },
    { label: 'Free Throws Attempted', key: 'freeThrowsAttempted' },
    { label: 'Free Throw %', key: 'freeThrowPct' },
    { label: 'Minutes', key: 'minutes' },
    { label: 'Avg Minutes', key: 'avgMinutes' },
    { label: 'Games Played', key: 'gamesPlayed' },
    { label: 'Games Started', key: 'gamesStarted' },
    { label: 'Double Doubles', key: 'doubleDouble' },
    { label: 'Triple Doubles', key: 'tripleDouble' }
  ],
  WNBA: [
    { label: 'Avg Points', key: 'avgPoints' },
    { label: 'Points', key: 'points' },
    { label: 'Avg Rebounds', key: 'avgRebounds' },
    { label: 'Rebounds', key: 'rebounds' },
    { label: 'Offensive Rebounds', key: 'offensiveRebounds' },
    { label: 'Defensive Rebounds', key: 'defensiveRebounds' },
    { label: 'Avg Assists', key: 'avgAssists' },
    { label: 'Assists', key: 'assists' },
    { label: 'Avg Blocks', key: 'avgBlocks' },
    { label: 'Blocks', key: 'blocks' },
    { label: 'Avg Steals', key: 'avgSteals' },
    { label: 'Steals', key: 'steals' },
    { label: 'Avg Turnovers', key: 'avgTurnovers' },
    { label: 'Turnovers', key: 'turnovers' },
    { label: 'Avg Fouls', key: 'avgFouls' },
    { label: 'Fouls', key: 'fouls' },
    { label: 'Field Goals Attempted', key: 'fieldGoalsAttempted' },
    { label: 'Field Goals Made', key: 'fieldGoalsMade' },
    { label: 'Field Goal %', key: 'fieldGoalPct' },
    { label: '3PT Attempted', key: 'threePointFieldGoalsAttempted' },
    { label: '3PT Made', key: 'threePointFieldGoalsMade' },
    { label: '3PT %', key: 'threePointFieldGoalPct' },
    { label: 'Free Throws Attempted', key: 'freeThrowsAttempted' },
    { label: 'Free Throws Made', key: 'freeThrowsMade' },
    { label: 'Free Throw %', key: 'freeThrowPct' },
    { label: 'Minutes', key: 'minutes' },
    { label: 'Avg Minutes', key: 'avgMinutes' },
    { label: 'Games Played', key: 'gamesPlayed' },
    { label: 'Games Started', key: 'gamesStarted' },
    { label: 'Double Doubles', key: 'doubleDouble' },
    { label: 'Triple Doubles', key: 'tripleDouble' }
  ],
  NHL: [
    // General Stats
    { label: 'Games', key: 'games', category: 'General' },
    { label: 'Games Started', key: 'gameStarted', category: 'General' },
    { label: 'Team Games Played', key: 'teamGamesPlayed', category: 'General' },
    { label: 'Time On Ice', key: 'timeOnIce', category: 'General' },
    { label: 'Time On Ice/Game', key: 'timeOnIcePerGame', category: 'General' },
    { label: 'Shifts', key: 'shifts', category: 'General' },
    { label: 'Shifts/Game', key: 'shiftsPerGame', category: 'General' },
    { label: 'Production', key: 'production', category: 'General' },
    { label: '+/-', key: 'plusMinus', category: 'General' },
    // Offensive Stats
    { label: 'Goals', key: 'goals', category: 'Offensive' },
    { label: 'Avg Goals', key: 'avgGoals', category: 'Offensive' },
    { label: 'Assists', key: 'assists', category: 'Offensive' },
    { label: 'Points', key: 'points', category: 'Offensive' },
    { label: 'Points/Game', key: 'pointsPerGame', category: 'Offensive' },
    { label: 'Shots', key: 'shotsTotal', category: 'Offensive' },
    { label: 'Avg Shots', key: 'avgShots', category: 'Offensive' },
    { label: 'Shooting %', key: 'shootingPct', category: 'Offensive' },
    { label: 'Power Play Goals', key: 'powerPlayGoals', category: 'Offensive' },
    { label: 'Power Play Assists', key: 'powerPlayAssists', category: 'Offensive' },
    { label: 'Short Handed Goals', key: 'shortHandedGoals', category: 'Offensive' },
    { label: 'Short Handed Assists', key: 'shortHandedAssists', category: 'Offensive' },
    { label: 'Game Winning Goals', key: 'gameWinningGoals', category: 'Offensive' },
    { label: 'Game Tying Goals', key: 'gameTyingGoals', category: 'Offensive' },
    { label: 'Total Faceoffs', key: 'totalFaceOffs', category: 'Offensive' },
    { label: 'Faceoffs Won', key: 'faceoffsWon', category: 'Offensive' },
    { label: 'Faceoffs Lost', key: 'faceoffsLost', category: 'Offensive' },
    { label: 'Faceoff %', key: 'faceoffPercent', category: 'Offensive' },
    { label: 'Shootout Attempts', key: 'shootoutAttempts', category: 'Offensive' },
    { label: 'Shootout Goals', key: 'shootoutGoals', category: 'Offensive' },
    { label: 'Shootout Shot %', key: 'shootoutShotPct', category: 'Offensive' },
    // Defensive/Goalie Stats
    { label: 'Wins', key: 'wins', category: 'Goalie' },
    { label: 'Losses', key: 'losses', category: 'Goalie' },
    { label: 'Ties', key: 'ties', category: 'Goalie' },
    { label: 'Goals Against', key: 'goalsAgainst', category: 'Goalie' },
    { label: 'Goals Against Avg', key: 'avgGoalsAgainst', category: 'Goalie' },
    { label: 'Saves', key: 'saves', category: 'Goalie' },
    { label: 'Save %', key: 'savePct', category: 'Goalie' },
    { label: 'Shots Against', key: 'shotsAgainst', category: 'Goalie' },
    { label: 'Avg Shots Against', key: 'avgShotsAgainst', category: 'Goalie' },
    { label: 'Shutouts', key: 'shutouts', category: 'Goalie' },
    { label: 'Overtime Losses', key: 'overtimeLosses', category: 'Goalie' },
    { label: 'Blocked Shots', key: 'blockedShots', category: 'Defensive' },
    { label: 'Hits', key: 'hits', category: 'Defensive' },
    { label: 'Shootout Saves', key: 'shootoutSaves', category: 'Goalie' },
    { label: 'Shootout Shots Against', key: 'shootoutShotsAgainst', category: 'Goalie' },
    { label: 'Shootout Save %', key: 'shootoutSavePct', category: 'Goalie' },
    { label: 'Empty Net Goals Against', key: 'emptyNetGoalsAgainst', category: 'Goalie' },
    { label: 'Even Strength Saves', key: 'evenStrengthSaves', category: 'Goalie' },
    { label: 'Power Play Saves', key: 'powerPlaySaves', category: 'Goalie' },
    { label: 'Short Handed Saves', key: 'shortHandedSaves', category: 'Goalie' },
    // Penalties
    { label: 'Penalty Minutes', key: 'penaltyMinutes', category: 'Penalties' },
    { label: 'Major Penalties', key: 'majorPenalties', category: 'Penalties' },
    { label: 'Minor Penalties', key: 'minorPenalties', category: 'Penalties' },
    { label: 'Match Penalties', key: 'matchPenalties', category: 'Penalties' },
    { label: 'Misconducts', key: 'misconducts', category: 'Penalties' },
    { label: 'Game Misconducts', key: 'gameMisconducts', category: 'Penalties' },
    { label: 'Fighting Penalties', key: 'fightingPenalties', category: 'Penalties' },
    { label: 'Avg Fights', key: 'avgFights', category: 'Penalties' },
    { label: 'Boarding Penalties', key: 'boardingPenalties', category: 'Penalties' },
    { label: 'Charging Penalties', key: 'chargingPenalties', category: 'Penalties' },
    { label: 'Hooking Penalties', key: 'hookingPenalties', category: 'Penalties' },
    { label: 'Tripping Penalties', key: 'trippingPenalties', category: 'Penalties' },
    { label: 'Slashing Penalties', key: 'slashingPenalties', category: 'Penalties' },
    { label: 'High Sticking Penalties', key: 'highStickingPenalties', category: 'Penalties' },
    { label: 'Cross Checking Penalties', key: 'crossCheckingPenalties', category: 'Penalties' },
    { label: 'Holding Penalties', key: 'holdingPenalties', category: 'Penalties' },
    { label: 'Interference Penalties', key: 'interferencePenalties', category: 'Penalties' },
    { label: 'Roughing Penalties', key: 'roughingPenalties', category: 'Penalties' },
    { label: 'Unsportsmanlike Penalties', key: 'unsportsmanlikePenalties', category: 'Penalties' },
    { label: 'Instigator Penalties', key: 'instigatorPenalties', category: 'Penalties' },
    { label: 'Stick Holding Penalties', key: 'stickHoldingPenalties', category: 'Penalties' },
    { label: 'Goalie Interference Penalties', key: 'goalieInterferencePenalties', category: 'Penalties' },
    { label: 'Elbowing Penalties', key: 'elbowingPenalties', category: 'Penalties' },
    { label: 'Diving Penalties', key: 'divingPenalties', category: 'Penalties' }
  ],
  MLB: [
    // Batting stats
    { label: 'Games Played', key: 'batting_gamesPlayed', category: 'Batting' },
    { label: 'At Bats', key: 'batting_atBats', category: 'Batting' },
    { label: 'Runs', key: 'batting_runs', category: 'Batting' },
    { label: 'Hits', key: 'batting_hits', category: 'Batting' },
    { label: 'Doubles', key: 'batting_doubles', category: 'Batting' },
    { label: 'Triples', key: 'batting_triples', category: 'Batting' },
    { label: 'Home Runs', key: 'batting_homeRuns', category: 'Batting' },
    { label: 'RBIs', key: 'batting_RBIs', category: 'Batting' },
    { label: 'Stolen Bases', key: 'batting_stolenBases', category: 'Batting' },
    { label: 'Caught Stealing', key: 'batting_caughtStealing', category: 'Batting' },
    { label: 'Walks', key: 'batting_walks', category: 'Batting' },
    { label: 'Strikeouts', key: 'batting_strikeouts', category: 'Batting' },
    { label: 'Batting Average', key: 'batting_avg', category: 'Batting' },
    { label: 'On Base %', key: 'batting_onBasePct', category: 'Batting' },
    { label: 'Slugging', key: 'batting_slugAvg', category: 'Batting' },
    { label: 'OPS', key: 'batting_OPS', category: 'Batting' },
    
    // Fielding stats
    { label: 'Games Played', key: 'fielding_gamesPlayed', category: 'Fielding' },
    { label: 'Innings', key: 'fielding_fullInningsPlayed', category: 'Fielding' },
    { label: 'Chances', key: 'fielding_totalChances', category: 'Fielding' },
    { label: 'Put Outs', key: 'fielding_putouts', category: 'Fielding' },
    { label: 'Assists', key: 'fielding_assists', category: 'Fielding' },
    { label: 'Errors', key: 'fielding_errors', category: 'Fielding' },
    { label: 'Double Plays', key: 'fielding_doublePlays', category: 'Fielding' },
    { label: 'Triple Plays', key: 'fielding_triplePlays', category: 'Fielding' },
    
    // Pitching stats
    { label: 'Games Played', key: 'pitching_gamesPlayed', category: 'Pitching' },
    { label: 'Games Started', key: 'pitching_gamesStarted', category: 'Pitching' },
    { label: 'Complete Games', key: 'pitching_completeGames', category: 'Pitching' },
    { label: 'Shutouts', key: 'pitching_shutouts', category: 'Pitching' },
    { label: 'Innings', key: 'pitching_innings', category: 'Pitching' },
    { label: 'Hits', key: 'pitching_hits', category: 'Pitching' },
    { label: 'Runs', key: 'pitching_runs', category: 'Pitching' },
    { label: 'Earned Runs', key: 'pitching_earnedRuns', category: 'Pitching' },
    { label: 'Home Runs', key: 'pitching_homeRuns', category: 'Pitching' },
    { label: 'Walks', key: 'pitching_walks', category: 'Pitching' },
    { label: 'Strikeouts', key: 'pitching_strikeouts', category: 'Pitching' },
    { label: 'Wins', key: 'pitching_wins', category: 'Pitching' },
    { label: 'Losses', key: 'pitching_losses', category: 'Pitching' },
    { label: 'Saves', key: 'pitching_saves', category: 'Pitching' },
    { label: 'Holds', key: 'pitching_holds', category: 'Pitching' },
    { label: 'Blown Saves', key: 'pitching_blownSaves', category: 'Pitching' },
    { label: 'ERA', key: 'pitching_ERA', category: 'Pitching' },
    { label: 'WHIP', key: 'pitching_WHIP', category: 'Pitching' }
  ],
  'V League': [
    // Player stats
    { label: 'Games Played', key: 'GP', category: 'General' },
    { label: 'Points', key: 'PTS', category: 'Scoring' },
    { label: 'Field Goals Made', key: 'FGM', category: 'Shooting' },
    { label: 'Field Goals Attempted', key: 'FGA', category: 'Shooting' },
    { label: 'Field Goal %', key: 'FG%', category: 'Shooting' },
    { label: '3-Pointers Made', key: '3PM', category: 'Shooting' },
    { label: '3-Pointers Attempted', key: '3PA', category: 'Shooting' },
    { label: '3-Point %', key: '3P%', category: 'Shooting' },
    { label: 'Free Throws Made', key: 'FTM', category: 'Shooting' },
    { label: 'Free Throws Attempted', key: 'FTA', category: 'Shooting' },
    { label: 'Free Throw %', key: 'FT%', category: 'Shooting' },
    { label: 'Offensive Rebounds', key: 'OREB', category: 'Rebounding' },
    { label: 'Defensive Rebounds', key: 'DREB', category: 'Rebounding' },
    { label: 'Total Rebounds', key: 'REB', category: 'Rebounding' },
    { label: 'Assists', key: 'AST', category: 'Playmaking' },
    { label: 'Steals', key: 'STL', category: 'Defense' },
    { label: 'Blocks', key: 'BLK', category: 'Defense' },
    { label: 'Turnovers', key: 'TOV', category: 'Other' }
  ],
  NFL: [
    // General Stats
    { label: 'Games Played (GP)', key: 'gamesPlayed', category: 'General' },
    { label: 'Fumbles (FUM)', key: 'fumbles', category: 'General' },
    { label: 'Fumbles Lost (LST)', key: 'fumblesLost', category: 'General' },
    { label: 'Fumble TDs (TD)', key: 'fumblesTouchdowns', category: 'General' },
    { label: 'Offensive 2PT Returns', key: 'offensiveTwoPtReturns', category: 'General' },
    { label: 'Offensive Fumble TDs', key: 'offensiveFumblesTouchdowns', category: 'General' },
    { label: 'Defensive Fumble TDs', key: 'defensiveFumblesTouchdowns', category: 'General' },
    
    // Passing (QB)
    { label: 'Completions (CMP)', key: 'passCompletions', category: 'Passing' },
    { label: 'Attempts (ATT)', key: 'passAttempts', category: 'Passing' },
    { label: 'Completion % (PCT)', key: 'completionPercentage', category: 'Passing' },
    { label: 'Passing Yards (YDS)', key: 'passYards', category: 'Passing' },
    { label: 'Yards per Attempt (YPA)', key: 'yardsPerPassAttempt', category: 'Passing' },
    { label: 'Touchdowns (TD)', key: 'passTouchdowns', category: 'Passing' },
    { label: 'Interceptions (INT)', key: 'interceptions', category: 'Passing' },
    { label: 'Longest Pass (LNG)', key: 'longestPass', category: 'Passing' },
    { label: 'Sacks Taken (SK)', key: 'sacksTaken', category: 'Passing' },
    { label: 'Sack Yards (SYD)', key: 'sackYards', category: 'Passing' },
    { label: 'Passer Rating (RATE)', key: 'passerRating', category: 'Passing' },
    { label: 'QBR', key: 'qbr', category: 'Passing' },
    { label: 'ESPN QBR', key: 'espnQBRating', category: 'Passing' },
    { label: 'Interception %', key: 'interceptionPct', category: 'Passing' },
    { label: 'Net Passing Yards', key: 'netPassingYards', category: 'Passing' },
    { label: 'Net Yards per Game', key: 'netPassingYardsPerGame', category: 'Passing' },
    { label: 'Net Total Yards', key: 'netTotalYards', category: 'Passing' },
    { label: 'Net Yards per Game', key: 'netYardsPerGame', category: 'Passing' },
    { label: 'Big Plays', key: 'passingBigPlays', category: 'Passing' },
    { label: 'First Downs', key: 'passingFirstDowns', category: 'Passing' },
    { label: 'Passing Fumbles', key: 'passingFumbles', category: 'Passing' },
    { label: 'Passing Fumbles Lost', key: 'passingFumblesLost', category: 'Passing' },
    { label: 'Touchdown %', key: 'passingTouchdownPct', category: 'Passing' },
    { label: 'Yards After Catch', key: 'passingYardsAfterCatch', category: 'Passing' },
    { label: 'Yards at Catch', key: 'passingYardsAtCatch', category: 'Passing' },
    { label: 'Yards per Game', key: 'passingYardsPerGame', category: 'Passing' },
    { label: 'Net Attempts', key: 'netPassingAttempts', category: 'Passing' },
    { label: 'Team Games', key: 'teamGamesPlayed', category: 'Passing' },
    { label: 'Total Offensive Plays', key: 'totalOffensivePlays', category: 'Passing' },
    { label: 'Points per Game', key: 'totalPointsPerGame', category: 'Passing' },
    { label: 'Total Yards', key: 'totalYards', category: 'Passing' },
    { label: 'Yards from Scrimmage', key: 'totalYardsFromScrimmage', category: 'Passing' },
    { label: '2PT Conversions', key: 'twoPointPassConvs', category: 'Passing' },
    { label: '2PT Passes', key: 'twoPtPass', category: 'Passing' },
    { label: '2PT Pass Attempts', key: 'twoPtPassAttempts', category: 'Passing' },
    { label: 'Yards from Scrimmage/G', key: 'yardsFromScrimmagePerGame', category: 'Passing' },
    { label: 'Yards per Completion', key: 'yardsPerCompletion', category: 'Passing' },
    { label: 'Yards per Game', key: 'yardsPerGame', category: 'Passing' },
    { label: 'Net Yards per Attempt', key: 'netYardsPerPassAttempt', category: 'Passing' },
    { label: 'Adjusted QBR', key: 'adjQBR', category: 'Passing' },
    { label: 'Quarterback Rating', key: 'quarterbackRating', category: 'Passing' },
    
    // Rushing (RB/QB/WR)
    { label: 'Attempts (ATT)', key: 'rushingAttempts', category: 'Rushing' },
    { label: 'Yards (YDS)', key: 'rushingYards', category: 'Rushing' },
    { label: 'Yards per Carry (AVG)', key: 'yardsPerRushAttempt', category: 'Rushing' },
    { label: 'Longest Run (LNG)', key: 'longestRush', category: 'Rushing' },
    { label: 'Touchdowns (TD)', key: 'rushTouchdowns', category: 'Rushing' },
    { label: 'Fumbles (FUM)', key: 'rushingFumbles', category: 'Rushing' },
    { label: 'Lost (LST)', key: 'rushingFumblesLost', category: 'Rushing' },
    { label: 'ESPN RB Rating', key: 'espnRBRating', category: 'Rushing' },
    { label: 'Big Plays', key: 'rushingBigPlays', category: 'Rushing' },
    { label: 'First Downs', key: 'rushingFirstDowns', category: 'Rushing' },
    { label: 'Yards per Game', key: 'rushingYardsPerGame', category: 'Rushing' },
    { label: '2PT Rush Conversions', key: 'twoPointRushConvs', category: 'Rushing' },
    { label: '2PT Rushes', key: 'twoPtRush', category: 'Rushing' },
    { label: '2PT Rush Attempts', key: 'twoPtRushAttempts', category: 'Rushing' },

    // Receiving (WR/TE/RB)
    { label: 'Targets (TGT)', key: 'receivingTargets', category: 'Receiving' },
    { label: 'Receptions (REC)', key: 'receptions', category: 'Receiving' },
    { label: 'Catch % (CATCH%)', key: 'catchPercentage', category: 'Receiving' },
    { label: 'Yards (YDS)', key: 'receivingYards', category: 'Receiving' },
    { label: 'Avg per Reception (AVG)', key: 'yardsPerReception', category: 'Receiving' },
    { label: 'Yards per Game (YPG)', key: 'receivingYardsPerGame', category: 'Receiving' },
    { label: 'Longest Reception (LNG)', key: 'longestReception', category: 'Receiving' },
    { label: 'Touchdowns (TD)', key: 'receivingTouchdowns', category: 'Receiving' },
    { label: 'Fumbles (FUM)', key: 'receivingFumbles', category: 'Receiving' },
    { label: 'Lost (LST)', key: 'receivingFumblesLost', category: 'Receiving' },
    { label: 'ESPN WR Rating', key: 'espnWRRating', category: 'Receiving' },
    { label: 'Big Plays', key: 'receivingBigPlays', category: 'Receiving' },
    { label: 'First Downs', key: 'receivingFirstDowns', category: 'Receiving' },
    { label: 'Yards After Catch', key: 'receivingYardsAfterCatch', category: 'Receiving' },
    { label: 'Yards at Catch', key: 'receivingYardsAtCatch', category: 'Receiving' },
    { label: '2PT Reception Conversions', key: 'twoPointRecConvs', category: 'Receiving' },
    { label: '2PT Receptions', key: 'twoPtReception', category: 'Receiving' },
    { label: '2PT Reception Attempts', key: 'twoPtReceptionAttempts', category: 'Receiving' },

    // Defense (Individual)
    { label: 'Total Tackles (TOT)', key: 'totalTackles', category: 'Defense' },
    { label: 'Solo (SOLO)', key: 'soloTackles', category: 'Defense' },
    { label: 'Assisted (AST)', key: 'assistedTackles', category: 'Defense' },
    { label: 'Sacks (SACK)', key: 'sacks', category: 'Defense' },
    { label: 'Interceptions (INT)', key: 'defensiveInterceptions', category: 'Defense' },
    { label: 'Passes Defended (PD)', key: 'passesDefended', category: 'Defense' },
    { label: 'Forced Fumbles (FF)', key: 'forcedFumbles', category: 'Defense' },
    { label: 'Fumble Recoveries (FR)', key: 'fumbleRecoveries', category: 'Defense' },
    { label: 'Defensive TDs (TD)', key: 'interceptionTouchdowns', category: 'Defense' },
    { label: 'Safeties (SFTY)', key: 'safeties', category: 'Defense' },
    { label: 'Blocked Kicks (BK)', key: 'kicksBlocked', category: 'Defense' },
    { label: 'Fumble Recovery Yards', key: 'fumbleRecoveryYards', category: 'Defense' },
    { label: 'Interception Yards', key: 'interceptionYards', category: 'Defense' },
    { label: 'Avg Interception Yards', key: 'avgInterceptionYards', category: 'Defense' },
    { label: 'Longest Interception', key: 'longestInterception', category: 'Defense' },
    { label: 'Stuffs', key: 'stuffs', category: 'Defense' },
    { label: 'Stuff Yards', key: 'stuffYards', category: 'Defense' },

    // Scoring Stats
    { label: 'Passing TDs', key: 'passingTouchdowns', category: 'Scoring' },
    { label: 'Rushing TDs', key: 'rushingTouchdowns', category: 'Scoring' },
    { label: 'Receiving TDs', key: 'receivingTouchdowns', category: 'Scoring' },
    { label: 'Return TDs', key: 'returnTouchdowns', category: 'Scoring' },
    { label: 'Total TDs', key: 'totalTouchdowns', category: 'Scoring' },
    { label: 'Two Point Conversions', key: 'totalTwoPointConvs', category: 'Scoring' },
    { label: 'Kick Extra Points', key: 'kickExtraPoints', category: 'Scoring' },
    { label: 'Field Goals', key: 'fieldGoals', category: 'Scoring' },
    { label: 'Total Points', key: 'totalPoints', category: 'Scoring' },
    { label: 'Defensive Points', key: 'defensivePoints', category: 'Scoring' },
    { label: 'Kick Extra Points Made', key: 'kickExtraPointsMade', category: 'Scoring' },
    { label: 'Misc Points', key: 'miscPoints', category: 'Scoring' },
    { label: '2PT Pass Conversions', key: 'twoPointPassConvs', category: 'Scoring' },
    { label: '2PT Rec Conversions', key: 'twoPointRecConvs', category: 'Scoring' },
    { label: '2PT Rush Conversions', key: 'twoPointRushConvs', category: 'Scoring' },
    { label: '1PT Safeties Made', key: 'onePtSafetiesMade', category: 'Scoring' },

    // Special Teams - Kicking
    { label: 'Field Goals Made (FGM)', key: 'fieldGoalsMade', category: 'Kicking' },
    { label: 'Field Goals Attempted (FGA)', key: 'fieldGoalAttempts', category: 'Kicking' },
    { label: 'FG % (FG%)', key: 'fieldGoalPercentage', category: 'Kicking' },
    { label: 'Longest FG (LNG)', key: 'longFieldGoalMade', category: 'Kicking' },
    { label: 'Extra Points Made (XPM)', key: 'extraPointsMade', category: 'Kicking' },
    { label: 'Extra Points Attempted (XPA)', key: 'extraPointAttempts', category: 'Kicking' },
    { label: 'Extra Point % (XP%)', key: 'extraPointPercentage', category: 'Kicking' },
    { label: 'Points (PTS)', key: 'totalKickingPoints', category: 'Kicking' },
    { label: 'FG Made 1-19', key: 'fieldGoalsMade1_19', category: 'Kicking' },
    { label: 'FG Made 20-29', key: 'fieldGoalsMade20_29', category: 'Kicking' },
    { label: 'FG Made 30-39', key: 'fieldGoalsMade30_39', category: 'Kicking' },
    { label: 'FG Made 40-49', key: 'fieldGoalsMade40_49', category: 'Kicking' },
    { label: 'FG Made 50+', key: 'fieldGoalsMade50', category: 'Kicking' },

    // Special Teams - Punting
    { label: 'Punts (PUNTS)', key: 'punts', category: 'Punting' },
    { label: 'Yards (YDS)', key: 'puntYards', category: 'Punting' },
    { label: 'Avg (AVG)', key: 'grossAvgPuntYards', category: 'Punting' },
    { label: 'Net Avg (NET)', key: 'netAvgPuntYards', category: 'Punting' },
    { label: 'Inside 20 (IN20)', key: 'puntsInside20', category: 'Punting' },
    { label: 'Touchbacks (TB)', key: 'puntTouchbacks', category: 'Punting' },
    { label: 'Longest Punt (LNG)', key: 'longestPunt', category: 'Punting' },
    { label: 'Blocked Punts (BP)', key: 'blockedPunts', category: 'Punting' },

    // Special Teams - Returns
    { label: 'Kick Returns: Attempts (ATT)', key: 'kickReturnAttempts', category: 'Returns' },
    { label: 'Kick Returns: Yards (YDS)', key: 'kickReturnYards', category: 'Returns' },
    { label: 'Kick Returns: Avg (AVG)', key: 'kickReturnAverage', category: 'Returns' },
    { label: 'Kick Returns: TDs', key: 'kickReturnTouchdowns', category: 'Returns' },
    { label: 'Kick Returns: Longest (LNG)', key: 'longestKickReturn', category: 'Returns' },
    { label: 'Punt Returns: Attempts (ATT)', key: 'puntReturnAttempts', category: 'Returns' },
    { label: 'Punt Returns: Yards (YDS)', key: 'puntReturnYards', category: 'Returns' },
    { label: 'Punt Returns: Avg (AVG)', key: 'puntReturnAverage', category: 'Returns' },
    { label: 'Punt Returns: TDs', key: 'puntReturnTouchdowns', category: 'Returns' },
    { label: 'Punt Returns: Longest (LNG)', key: 'longestPuntReturn', category: 'Returns' },
    { label: 'Kick Returns: Fair Catches', key: 'kickReturnFairCatches', category: 'Returns' },
    { label: 'Punt Returns: Fair Catches', key: 'puntReturnFairCatches', category: 'Returns' }
  ]
};

export const nbaTeamStats = [
  { label: 'Wins', key: 'wins' },
  { label: 'Losses', key: 'losses' },
  { label: 'Win %', key: 'winPercentage' },
  { label: 'Games Behind', key: 'gamesBehind' },
  { label: 'Home Record', key: 'homeRecord' },
  { label: 'Away Record', key: 'awayRecord' },
  { label: 'Conference Record', key: 'conferenceRecord' },
  { label: 'Points Per Game', key: 'pointsPerGame' },
  { label: 'Opponent Points Per Game', key: 'opponentPointsPerGame' },
  { label: 'Point Differential', key: 'pointDifferential' },
  { label: 'Streak', key: 'streak' },
  { label: 'Last 10 Games', key: 'lastTenGames' }
];

export const wnbaTeamStats = [
  { label: 'Wins', key: 'wins' },
  { label: 'Losses', key: 'losses' },
  { label: 'Win %', key: 'winPercentage' },
  { label: 'Games Behind', key: 'gamesBehind' },
  { label: 'Home Record', key: 'homeRecord' },
  { label: 'Away Record', key: 'awayRecord' },
  { label: 'Conference Record', key: 'conferenceRecord' },
  { label: 'Points Per Game', key: 'pointsPerGame' },
  { label: 'Opponent Points Per Game', key: 'opponentPointsPerGame' },
  { label: 'Point Differential', key: 'pointDifferential' },
  { label: 'Streak', key: 'streak' },
  { label: 'Last 10 Games', key: 'lastTenGames' }
];

export const mlbTeamStats = [
  { label: 'Wins', key: 'wins' },
  { label: 'Losses', key: 'losses' },
  { label: 'Win %', key: 'winpercent' },
  { label: 'Games Behind', key: 'gamesbehind' },
  { label: 'Home Record', key: 'home' },
  { label: 'Road Record', key: 'road' },
  { label: 'Intraleague Record', key: 'vsconf' },
  { label: 'Runs Per Game', key: 'avgpointsfor' },
  { label: 'Runs Allowed Per Game', key: 'avgpointsagainst' },
  { label: 'Run Differential', key: 'differential' },
  { label: 'Streak', key: 'streak' },
  { label: 'Last 10 Games', key: 'lasttengames' }
];

export const nflTeamStats = [
  // Offense
  { label: 'Passing Yards (YDS)', key: 'netPassingYards', category: 'Offense' },
  { label: 'Rushing Yards (YDS)', key: 'rushingYards', category: 'Offense' },
  { label: 'Total Yards (YDS)', key: 'totalYards', category: 'Offense' },
  { label: 'Yards per Play (AVG)', key: 'yardsPerPlay', category: 'Offense' },
  { label: 'Points per Game (PTS/G)', key: 'totalPointsPerGame', category: 'Offense' },
  { label: '1st Downs (1D)', key: 'totalFirstDowns', category: 'Offense' },
  { label: '3rd Down % (3D%)', key: 'thirdDownConversionPct', category: 'Offense' },
  { label: '4th Down % (4D%)', key: 'fourthDownConversionPct', category: 'Offense' },
  { label: 'Red Zone % (RZ%)', key: 'redzoneScoringPct', category: 'Offense' },
  { label: 'Turnovers (TO)', key: 'totalGiveaways', category: 'Offense' },
  { label: 'Time of Possession (TOP)', key: 'possessionTimeSeconds', category: 'Offense' },

  // Defense
  { label: 'Points Allowed (PA)', key: 'pointsAllowed', category: 'Defense' },
  { label: 'Total Yards Allowed (YDSA)', key: 'totalYardsAllowed', category: 'Defense' },
  { label: 'Passing Yards Allowed (PYDSA)', key: 'passingYardsAllowed', category: 'Defense' },
  { label: 'Rushing Yards Allowed (RYDSA)', key: 'rushingYardsAllowed', category: 'Defense' },
  { label: 'Takeaways (TAKE)', key: 'totalTakeaways', category: 'Defense' },
  { label: 'Red Zone % Allowed (RZA)', key: 'redZoneAllowedPct', category: 'Defense' },
  { label: '3rd Down % Allowed (3DA)', key: 'thirdDownAllowedPct', category: 'Defense' },
  { label: '4th Down % Allowed (4DA)', key: 'fourthDownAllowedPct', category: 'Defense' },

  // Special Teams
  { label: 'Field Goal % (FG%)', key: 'fieldGoalPct', category: 'Special Teams' },
  { label: 'Extra Point % (XP%)', key: 'extraPointPct', category: 'Special Teams' },
  { label: 'Punt Avg (PUNT AVG)', key: 'grossAvgPuntYards', category: 'Special Teams' },
  { label: 'Net (NET)', key: 'netAvgPuntYards', category: 'Special Teams' },
  { label: 'Punts Inside 20 (IN20)', key: 'puntsInside20', category: 'Special Teams' },
  { label: 'Kick Return Avg (KR AVG)', key: 'avgKickoffReturnYards', category: 'Special Teams' },
  { label: 'Punt Return Avg (PR AVG)', key: 'avgPuntReturnYards', category: 'Special Teams' },
  { label: 'Special Teams TDs (STTD)', key: 'specialTeamsTDs', category: 'Special Teams' },
  { label: 'Blocked Kicks (BK)', key: 'blockedKicks', category: 'Special Teams' },
  
  // Penalties
  { label: 'Total Penalties (PEN)', key: 'totalPenalties', category: 'Penalties' },
  { label: 'Penalty Yards (PEN YDS)', key: 'totalPenaltyYards', category: 'Penalties' },
  { label: 'Penalties per Game (PEN/G)', key: 'penaltiesPerGame', category: 'Penalties' }
];

export const nhlTeamStats = [
  // Core standings
  { label: 'Wins', key: 'wins' },
  { label: 'Losses', key: 'losses' },
  { label: 'Games Played', key: 'gamesplayed' },
  { label: 'Games Behind', key: 'gamesbehind' },
  { label: 'Points For', key: 'pointsfor' },
  { label: 'Points Against', key: 'pointsagainst' },
  { label: 'Point Differential', key: 'pointdifferential' },
  { label: 'Points Diff', key: 'pointsdiff' },
  { label: 'Differential', key: 'differential' },
  { label: 'Home Record', key: 'home' },
  { label: 'Road Record', key: 'road' },
  { label: 'Division Record', key: 'vsdiv' },
  { label: 'Total Record', key: 'total' },
  { label: 'Last 10 Games', key: 'lasttengames' },
  { label: 'Streak', key: 'streak' },
  // Overtime/Shootout standings
  { label: 'OT Losses', key: 'otlosses' },
  { label: 'Overtime Wins', key: 'overtimewins' },
  { label: 'Shootout Losses', key: 'shootoutlosses' },
  { label: 'Shootout Wins', key: 'shootoutwins' },
  // Regulation
  { label: 'Regulation Losses', key: 'reglosses' },
  { label: 'Regulation Wins', key: 'regwins' },
  { label: 'ROT Losses', key: 'rotlosses' },
  { label: 'ROT Wins', key: 'rotwins' },
  // Playoff
  { label: 'Playoff Seed', key: 'playoffseed' },
  // Game Stats
  { label: 'Games', key: 'games' },
  { label: 'Time On Ice', key: 'timeOnIce' },
  { label: 'Time On Ice/Game', key: 'timeOnIcePerGame' },
  { label: 'Plus/Minus', key: 'plusMinus' },
  { label: 'Production', key: 'production' },
  { label: 'Shifts', key: 'shifts' },
  // Offensive Stats
  { label: 'Goals', key: 'goals' },
  { label: 'Assists', key: 'assists' },
  { label: 'Points', key: 'points' },
  { label: 'Faceoffs Won', key: 'faceoffsWon' },
  { label: 'Faceoffs Lost', key: 'faceoffsLost' },
  { label: 'Faceoff %', key: 'faceoffPercent' },
  { label: 'Game Winning Goals', key: 'gameWinningGoals' },
  { label: 'Power Play Goals', key: 'powerPlayGoals' },
  { label: 'Power Play Assists', key: 'powerPlayAssists' },
  { label: 'Short Handed Goals', key: 'shortHandedGoals' },
  { label: 'Short Handed Assists', key: 'shortHandedAssists' },
  { label: 'Shots', key: 'shotsTotal' },
  { label: 'Shooting %', key: 'shootingPct' },
  { label: 'Shootout Attempts', key: 'shootoutAttempts' },
  { label: 'Shootout Goals', key: 'shootoutGoals' },
  { label: 'Shootout Shot %', key: 'shootoutShotPct' },
  // Defensive Stats
  { label: 'Goals Against Avg', key: 'avgGoalsAgainst' },
  { label: 'Goals Against', key: 'goalsAgainst' },
  { label: 'Saves', key: 'saves' },
  { label: 'Save %', key: 'savePct' },
  { label: 'Shots Against', key: 'shotsAgainst' },
  { label: 'Overtime Losses', key: 'overtimeLosses' },
  { label: 'Shootout Saves', key: 'shootoutSaves' },
  { label: 'Shootout Shots Against', key: 'shootoutShotsAgainst' },
  { label: 'Shootout Save %', key: 'shootoutSavePct' },
  // Penalties
  { label: 'Penalty Minutes', key: 'penaltyMinutes' }
];

export const vLeagueTeamStats = [
  { label: 'Team', key: 'Team' },
  { label: 'Wins', key: 'W' },
  { label: 'Losses', key: 'L' },
  { label: 'Win %', key: 'WIN%' },
  { label: 'Points', key: 'PTS' },
  { label: 'Field Goals Made', key: 'FGM' },
  { label: 'Field Goals Attempted', key: 'FGA' },
  { label: 'Field Goal %', key: 'FG%' },
  { label: '3-Pointers Made', key: '3PM' },
  { label: '3-Pointers Attempted', key: '3PA' },
  { label: '3-Point %', key: '3P%' },
  { label: 'Free Throws Made', key: 'FTM' },
  { label: 'Free Throws Attempted', key: 'FTA' },
  { label: 'Free Throw %', key: 'FT%' },
  { label: 'Offensive Rebounds', key: 'OREB' },
  { label: 'Defensive Rebounds', key: 'DREB' },
  { label: 'Total Rebounds', key: 'REB' },
  { label: 'Assists', key: 'AST' },
  { label: 'Turnovers', key: 'TOV' },
  { label: 'Steals', key: 'STL' },
  { label: 'Blocks', key: 'BLK' },
  { label: 'Personal Fouls', key: 'PF' },
  { label: 'Fouls Drawn', key: 'PFD' }
];

export const teamStatsByLeagueData = {
  NBA: nbaTeamStats,
  WNBA: wnbaTeamStats,
  NFL: nflTeamStats,
  MLB: mlbTeamStats,
  NHL: nhlTeamStats,
  'V League': vLeagueTeamStats
};

